<?php

namespace MIH\GsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LignefraishorsforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraishorsforfaitRepository extends EntityRepository
{
}
