<?php

namespace MIH\GsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LignefraisforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignefraisforfaitRepository extends EntityRepository
{
}
